function report=validateProblem(problem,mesh,state,time,options)
%VALIDATEPROBLEM Perform optional deep checks for a TVD2 problem instance.

if nargin<4,time=0;end
if nargin<5,options=struct();end
options.RuntimeChecks=true;
requiredMesh={'FaceX','CellX','CellWidth','CellMeasure','CellCount'};
for index=1:numel(requiredMesh)
    assert(isfield(mesh,requiredMesh{index}), ...
        'tvd2tools:Mesh','Mesh is missing %s.',requiredMesh{index});
end
assert(size(state,2)==mesh.CellCount && all(isfinite(state),'all'), ...
    'tvd2tools:State','State must be finite with one column per cell.');
assert(isfield(problem,'Boundary') && isfield(problem.Boundary,'Left') ...
    && isfield(problem.Boundary,'Right'), ...
    'tvd2tools:Boundary','Both physical boundaries must be explicit.');
[derivative,details]=tvd2.spatialOperator(problem,time,state,mesh,options);
transportPart=derivative-details.Source;
weightedRate=sum(transportPart.*mesh.CellMeasure,2);
boundaryRate=details.FaceFlux(:,1)-details.FaceFlux(:,end);
closureError=weightedRate-boundaryRate;
report=struct('Passed',all(isfinite(derivative),'all') ...
    && norm(closureError,inf)<=1e3*eps(max(1,norm(boundaryRate,inf))), ...
    'StateSize',size(state),'FaceFluxSize',size(details.FaceFlux), ...
    'ConservationClosureInf',norm(closureError,inf), ...
    'EffectiveOrder',details.Reconstruction.EffectiveOrder, ...
    'Limiter',details.Reconstruction.Limiter);
if ~report.Passed
    error('tvd2tools:ValidationFailed', ...
        'The sampled problem failed finite-value or conservation checks.');
end
end
